#!/bin/bash -v
sudo rm -rf ruby-2.3.1
tar -zxvf ruby-2.3.1.tar.gz
cd ruby-2.3.1
./configure --prefix=/usr/local --program-suffix=231 --enable-shared --libdir=/usr/local/lib --disable-install-doc
make -j9
sudo make install
